# -*- coding: utf-8 -*-
"""Anomaly_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w2vA-WuWYs7m6IQQHWvKfvtLyq294w3I
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

!pip install ucimlrepo

from ucimlrepo import fetch_ucirepo
from sklearn.ensemble import IsolationForest

air_quality = fetch_ucirepo(id=360)
air_quality

#Converting dictionary to dataframe
data=air_quality.data.features
data.head()

data.isna().sum()

df=data[['CO(GT)','C6H6(GT)','NOx(GT)','NO2(GT)']]
df.head()

df.dtypes

#Parameters of isolation tree
n_estimators=100 # number of trees inthe forest
max_samples='auto' #number of samples to draw from the data
contamination=0.1 #percentage of outliers in the data
sample_size=256

model=IsolationForest(n_estimators=n_estimators,max_samples=sample_size,contamination=contamination,random_state=42)
model.fit(df)

feature_cols = ['CO(GT)','C6H6(GT)','NOx(GT)','NO2(GT)']
anomaly_labels=model.predict(df[feature_cols])
df['anomaly'] = anomaly_labels
# -1 is abnormal and 1 for normal
df.head()

# Check the number of anomaly labels
df['anomaly'].value_counts()

fig, axes = plt.subplots(1,2,figsize=(14,5))
normal = df[df['anomaly']==1]
anomaly = df[df['anomaly']==-1]
#plot co vs c6h6
axes[0].scatter(normal['CO(GT)'],normal['C6H6(GT)'],color='red',label='Normal',alpha=0.6,s=30)
axes[0].scatter(normal['CO(GT)'],normal['C6H6(GT)'],color='green',label='Anomaly',alpha=0.8,s=50,marker='x')
axes[0].set_xlabel('CO(GT)')
axes[0].set_ylabel('C6H6(GT)')
axes[0].legend()
axes[0].grid(True,alpha=0.3)
#plot nox vs no2
axes[1].scatter(normal['NOx(GT)'],normal['NO2(GT)'],color='red',label='Normal',alpha=0.6,s=30)
axes[1].scatter(normal['NOx(GT)'],normal['NO2(GT)'],color='blue',label='Anomaly',alpha=0.6,s=30,marker='x')
axes[1].set_xlabel('NOx(GT)')
axes[1].set_ylabel('NO2(GT)')
axes[1].legend()
axes[1].grid(True,alpha=0.3)
plt.tight_layout()
plt.show()

# to save model in local server
# import joblib
# model_path='D:\folder-name\modelname.pkl'
# joblib.dump(model,model_path)

